Lab03/models/Continent.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

class Continent extends ActiveRecord
{

}

Lab03/controllers/ContinentController.php
<?php

namespace app\controllers;

use app\models\Continent;
use app\models\Country;
use yii\data\ActiveDataProvider;
use yii\web\Controller;

class ContinentController extends Controller
{
    public function actionIndex()
    {
        $continents = Continent::find()->asArray()->all();
        return $this->render('index', ['continents' => $continents]);
    }
    public function actionView($code = "AF", $continent_id = 1)
    {
        $continent = Continent::find()->where(['continent_id' => $continent_id])->one();
        $countriesDataProvider = new ActiveDataProvider([
            'query' => Country::find()->where(['continent_id' => $continent_id]),
            'pagination' => [
                'pageSize' => 20,
            ]
        ]);
        return $this->render('view', compact(['continent', 'countriesDataProvider']));
    }
}

Lab03/controllers/CountryController.php
<?php

namespace app\controllers;

use yii\web\Controller;
use app\models\Country;

class CountryController extends Controller
{
    public function actionView($country_code)
    {
        $country = Country::find()->where(['code' => $country_code])->one();
        return $this->render('index', ['country' => $country]);
    }
}

Lab03/views/continent/_country.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>
<a href="<?= Url::to(['country/view', 'country_code' => $model->code]); ?>" class="list-group-item list-group-item-action">
    <?= Html::img('@web/images/countries/png100px/' . strtolower($model['code']) . '.png', ['alt' => $model['name']]) ?>
    <?= Html::encode($model->name) ?>
</a>

Lab03/views/continent/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

?>
<div class="row">
    <?php foreach ($continents as $continentItem): ?>
        <div class="col-6 col-md-4">
            <div class="card p-4 mb-5">
                <?= Html::img('@web/images/continents/' . strtolower($continentItem['code']) . '.png', ['alt' => $continentItem['name']]) ?>
                <div class="card-body">
                    <h5 class="card-title"><a href='<?= Url::to(['continent/view', 'continent_id' => $continentItem['continent_id']]); ?>'>
                            <?= Html::encode($continentItem['name']) ?></a></h5>
                    <p class="card-text"><?= Html::encode($continentItem['description']) ?></p>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

Lab03/views/continent/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ListView;
$this->title = $continent->name;
$this->params['breadcrumbs'][] = ['label' => 'Continents', 'url' => ['continent/index']];
$this->params['breadcrumbs'][] = ['label' => $continent['name'], 'url' => ['continent/view', 'code' => $continent['code']]];
?>

<section id="continent-view">
    <div class="container">
        <h1><?= Html::encode($this->title) ?></h1>
        <p><?= Html::encode($continent->description) ?></p>
        <?= ListView::widget([
            'dataProvider' => $countriesDataProvider,
            'itemView' => '_country',
            'layout' => "{items}\n{summary}\n{pager}",
            'options' => [
                'class' => 'list-group'
            ],
            'itemOptions' => [
                'tag' => false,
            ],
        ]); ?>
    </div>
</section>